# Most of the parameters will be imported from the training config
src:
  ckpt: 'ckpt/new_yungsung_sd0/best_att.pth' #'ckpt/good_model/common_voice_sd0/best_ctc.pth' #'ckpt/new_yungsung_sd0/best_att.pth'
  config: 'config/hyspeech/new_yungsung.yaml'
data:
  corpus:
    name: 'Dysar'
    dev_split: ['dev']
    test_split: ['']
decode:
  beam_size: 2
  min_len_ratio: 0.01
  max_len_ratio: 0.3
  lm_path: #'lm_bznsyp_sd0/best_ppx.pth' #'ckpt/lm_example_sd0/best_ppx.pth'
  lm_config: #'config/hyspeech/lm_bznsyp.yaml'
  lm_weight: 0.0
  ctc_weight: 1.0
